### ISSUE TITLE
Is pytest-expect v1.1.0 is compatible with python3.11

### ISSUE THREAD

**Issue by vivek-crest** [gsnedders/pytest-expect#18]
The [Pypi documentation](https://pypi.org/project/pytest-expect/) mentions that pytest-expect v1.1.0 is compatible with Python 3.
Does this claim that the library is compatible with Python 3.11.x as well?
If not, is there a plan to release a Python 3.11.x compatible version?

**Comment by gsnedders** [comment]
It should work with all current versions of Python 3, including 3.11.

**Comment by vivek-crest** [comment]
Thanks @gsnedders .
